# Generated by Django 4.1.7 on 2023-02-18 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        choices=[("CREATE", "CREATE"), ("READ", "READ")],
                        max_length=11,
                        verbose_name="contributor permissions",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("AUTHOR", "AUTHOR"), ("CONTRIBUTOR", "CONTRIBUTOR")],
                        max_length=11,
                        verbose_name="contributor role",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="project title"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=2000, verbose_name="project description"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("BACKEND", "BACKEND"),
                            ("FRONTEND", "FRONTEND"),
                            ("iOS", "iOS"),
                            ("ANDROID", "ANDROID"),
                        ],
                        max_length=8,
                        verbose_name="project type",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_author",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="issue title")),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=2000, verbose_name="issue description"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "LOW"),
                            ("MEDIUM", "MEDIUM"),
                            ("HIGH", "HIGH"),
                        ],
                        max_length=6,
                        verbose_name="issue priority",
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("TASK", "TASK"),
                            ("BUG", "BUG"),
                            ("IMPROVEMENT", "IMPROVEMENT"),
                        ],
                        max_length=11,
                        verbose_name="issue tag",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ASSIGNED", "ASSIGNED"),
                            ("IN PROGRESS", "IN PROGRESS"),
                            ("RESOLVED", "RESOLVED"),
                        ],
                        max_length=11,
                        verbose_name="issue status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="issue created at"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issue_assigned_to",
                        to="projects.contributor",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issue_author",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_concerned",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contributor",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributor_project",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="contributor",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        max_length=2000, verbose_name="comment description"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="comment created date, time"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_author",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issue_comment",
                        to="projects.issue",
                    ),
                ),
            ],
        ),
    ]
