# Generated by Django 4.1.7 on 2023-02-23 13:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contributor",
            name="permission",
        ),
    ]
