# Generated by Django 4.1.7 on 2023-02-27 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0002_remove_contributor_permission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="assigned_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issue_assigned_to",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
