# Generated by Django 4.1.7 on 2023-02-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_alter_issue_assigned_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="project",
            field=models.IntegerField(),
        ),
    ]
